# Generated by Django 5.1.5 on 2025-02-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_joining',
            field=models.DateTimeField(),
        ),
    ]
